version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - ls -al 
      - pwd
      - echo $CODEBUILD_SRC_DIR
  build:
    commands:
      - npm run build
      - ls -al
      - pwd
    
artifacts:
  base-directory: build
  files:
    - '**/*'
  name: AP-SOUTHEAST-2
cache:
  paths:
    - './node_modules/**/*'